// Personal Info
export const SET_PERSONAL_INFO_INPUT = 'SET_PERSONAL_INFO_INPUT';

// Career summary
export const SET_PROFILE_SUMMARY_INPUT = 'SET_PROFILE_SUMMARY_INPUT';

// Address
export const SET_ADDRESS_INPUT = 'SET_ADDRESS_INPUT';

// Website input
export const SET_WEBSITE_INPUT = 'SET_WEBSITE_INPUT';

// Link fields
export const ADD_MORE_LINK_FIELD = 'ADD_MORE_LINK_FIELD';
export const UPDATE_MORE_LINK_FIELD = 'UPDATE_MORE_LINK_FIELD';
export const REMOVE_MORE_LINK_FIELD = 'REMOVE_MORE_LINK_FIELD';
export const REMOVE_ALL_MORE_LINK_FIELD = 'REMOVE_ALL_MORE_LINK_FIELD';

// Work Experience Fields
export const ADD_WORK_EXPERIENCE_FIELD = 'ADD_WORK_EXPERIENCE_FIELD';
export const UPDATE_WORK_EXPERIENCE_FIELD = 'UPDATE_WORK_EXPERIENCE_FIELD';
export const REMOVE_WORK_EXPERIENCE_FIELD = 'REMOVE_WORK_EXPERIENCE_FIELD';
export const REMOVE_ALL_WORK_EXPERIENCE_FIELD =
  'REMOVE_ALL_WORK_EXPERIENCE_FIELD';

// Education Fields
export const ADD_EDUCATION_FIELD = 'ADD_EDUCATION_FIELD';
export const UPDATE_EDUCATION_FIELD = 'UPDATE_EDUCATION_FIELD';
export const REMOVE_EDUCATION_FIELD = 'REMOVE_EDUCATION_FIELD';
export const REMOVE_ALL_EDUCATION_FIELD = 'REMOVE_ALL_EDUCATION_FIELD';

// Skill Fields
export const ADD_SKILL_FIELD = 'ADD_SKILL_FIELD';
export const UPDATE_SKILL_FIELD = 'UPDATE_SKILL_FIELD';
export const REMOVE_SKILL_FIELD = 'REMOVE_SKILL_FIELD';
export const REMOVE_ALL_SKILL_FIELD = 'REMOVE_ALL_SKILL_FIELD';

// Project Fields
export const ADD_PROJECT_FIELD = 'ADD_PROJECT_FIELD';
export const UPDATE_PROJECT_FIELD = 'UPDATE_PROJECT_FIELD';
export const REMOVE_PROJECT_FIELD = 'REMOVE_PROJECT_FIELD';
export const REMOVE_ALL_PROJECT_FIELD = 'REMOVE_ALL_PROJECT_FIELD';

// Certification Fields
export const ADD_CERTIFICATION_FIELD = 'ADD_CERTIFICATION_FIELD';
export const UPDATE_CERTIFICATION_FIELD = 'UPDATE_CERTIFICATION_FIELD';
export const REMOVE_CERTIFICATION_FIELD = 'REMOVE_CERTIFICATION_FIELD';
export const REMOVE_ALL_CERTIFICATION_FIELD = 'REMOVE_ALL_CERTIFICATION_FIELD';

// Award Fields
export const ADD_AWARD_FIELD = 'ADD_AWARD_FIELD';
export const UPDATE_AWARD_FIELD = 'UPDATE_AWARD_FIELD';
export const REMOVE_AWARD_FIELD = 'REMOVE_AWARD_FIELD';
export const REMOVE_ALL_AWARD_FIELD = 'REMOVE_ALL_AWARD_FIELD';

// Language Fields
export const ADD_LANGUAGE_FIELD = 'ADD_LANGUAGE_FIELD';
export const UPDATE_LANGUAGE_FIELD = 'UPDATE_LANGUAGE_FIELD';
export const REMOVE_LANGUAGE_FIELD = 'REMOVE_LANGUAGE_FIELD';
export const REMOVE_ALL_LANGUAGE_FIELD = 'REMOVE_ALL_LANGUAGE_FIELD';

// Hobby Fields
export const ADD_HOBBY_FIELD = 'ADD_HOBBY_FIELD';
export const UPDATE_HOBBY_FIELD = 'UPDATE_HOBBY_FIELD';
export const REMOVE_HOBBY_FIELD = 'REMOVE_HOBBY_FIELD';
export const REMOVE_ALL_HOBBY_FIELD = 'REMOVE_ALL_HOBBY_FIELD';

// Skip Fields
export const SET_SKIP_FIELD = 'SET_SKIP_FIELD';
